# Definim el tipus Role perque Prisma l'injecti directament sense mapejos
type Role {
  id: ID!
  description: String!
}

# Definicio de l'Usuari (mirall exacte de Prisma)
type User {
  id: ID!
  code: String!           # Añadimos el código de socio que genera Prisma
  firstName: String!
  lastName1: String!
  lastName2: String
  dni: String!
  phone: String
  email: String!
  birthDate: String
  createdAt: String!      # Antes join_date
  deletedAt: String       # Antes leave_date
  profileImage: String
  roles: [Role!]!         # Ahora devuelve una lista de objetos Role
}

# Payload per a l'autenticacio
type AuthPayload {
  token: String!
  user: User!
}

# Input de Registre (tambe en camelCase perque coincideixi amb el frontend)
input RegisterUserInput {
  firstName: String!
  lastName1: String!
  lastName2: String
  dni: String!
  phone: String
  email: String!
  password: String! 
  birthDate: String!
  profileImage: String
  roles: [String!]
}

input UpdateUserInput {
  firstName: String
  lastName1: String
  lastName2: String
  dni: String
  phone: String
  email: String
  birthDate: String
  profileImage: String
}

extend type Query {
  getUserById(id: ID!): User
  getAllUsers: [User!]!
  me: User
}

extend type Mutation {
  registerUser(input: RegisterUserInput!): AuthPayload!
  loginUser(email: String!, password: String!): AuthPayload!
  updateUser(id: ID, input: UpdateUserInput!): User!
  changePassword(oldPassword: String!, newPassword: String!): Boolean!
}