type Query {
  getAllNews: [News!]!
  getNewsBySlug(slug: String!): News
}

extend type Mutation {
  createNews(input: CreateNewsInput!): News!
  updateNews(id: Int!, input: UpdateNewsInput!): News!
}

type News {
  new_id: Int!
  title: String!
  short_descr: String!
  sections: [String!]!
  creation_date: String!
  publication_date: String!
  public: Boolean!
  author: String!
  image: Image!
  slug: String!
}

input CreateNewsInput {
  title: String!
  short_descr: String!
  sections: [String!]!
  publication_date: String!
  public: Boolean
  author: String!
}

input UpdateNewsInput {
  title: String
  short_descr: String
  sections: [String!]
  publication_date: String
  public: Boolean
  author: String
  slug: String
}