# Definición del Usuario (sin exponer la contraseña)
type User {
  id: ID!
  first_name: String!
  last_name_1: String!
  last_name_2: String
  dni: String!
  phone: String
  email: String!
  birth_date: String!
  join_date: String!
  leave_date: String
  fee_status: String!
  roles: [String!]!
  sections: [String!]!
}

# Payload para autenticación
type AuthPayload {
  token: String!
  user: User!
}

# Input de Registro
input RegisterUserInput {
  first_name: String!
  last_name_1: String!
  last_name_2: String
  dni: String!
  phone: String
  email: String!
  password: String! # Recibe el string ya encriptado desde Astro
  birth_date: String!
  roles: [String!]
  sections: [String!]
}

input UpdateUserInput {
  first_name: String
  last_name_1: String
  last_name_2: String
  dni: String
  phone: String
  email: String
  birth_date: String
}

type Query {
  getUserById(id: ID!): User
  getAllUsers: [User!]!
  me: User
}

type Mutation {
  registerUser(input: RegisterUserInput!): AuthPayload!
  loginUser(email: String!, password: String!): AuthPayload!
  updateUser(input: UpdateUserInput!): User!
  changePassword(oldPassword: String!, newPassword: String!): Boolean!
}