# Definicio de l'entitat Section
type Section {
  id: ID!
  name: String!
  description: String
  createdAt: String!
  publishedAt: String
  isActive: Boolean!

  mainNews: News
  
  # Relaciones (GraphQL pedirá estos datos a Prisma cuando el frontend los solicite)
  news: [News!]!
  activities: [Activity!]!
  roles: [Role!]!
}

# Input per CREAR una seccio nova
# Nomes demanem l'essencial. L'ID i el createdAt els genera la BD automaticament.
input CreateSectionInput {
  name: String!
  description: String
  isActive: Boolean
  publishedAt: String
  mainNews: CreateSectionMainNewsInput!
}

input CreateSectionMainNewsInput {
  title: String!
  shortDescription: String!
  longDescription: String!
  status: String
  type: String
  mainImage: String
  secondaryImage: String
}

input UpdateSectionMainNewsInput {
  title: String
  shortDescription: String
  longDescription: String
  status: String
}

# Input per MODIFICAR una seccio existent
# Tots els camps son opcionals per permetre actualitzacions parcials
input UpdateSectionInput {
  name: String
  description: String
  isActive: Boolean
  publishedAt: String
  mainNews: UpdateSectionMainNewsInput
}

# Consultes (Queries)
extend type Query {
  getAllSections: [Section!]!
  getSectionById(id: ID!): Section
}

# Modificacions (Mutations)
extend type Mutation {
  createSection(input: CreateSectionInput!): Section!
  updateSection(id: ID!, input: UpdateSectionInput!): Section!
}