// This file was generated by Prisma, and assumes you have installed the following:
// npm install --save-dev prisma dotenv
require("dotenv/config");
const { defineConfig } = require("prisma/config");



module.exports = defineConfig({
  schema: "prisma/schema.prisma",
  migrations: {
    path: "prisma/migrations",
    seed: 'npx tsx ./prisma/seed_db.ts'
  },
  datasource: {
    ...(process.env["DATABASE_URL"] && { url: process.env["DATABASE_URL"] }),
  },
});
